import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi, beforeEach } from 'vitest'
import AskHRI from './AskHRI'
import { ApiError } from '../api/client'
import { askHRI } from '../api/endpoints'

vi.mock('../api/endpoints', () => ({
  askHRI: vi.fn(),
}))

function renderAt(path = '/ask') {
  return render(
    <MemoryRouter initialEntries={[path]}>
      <Routes>
        <Route path="/ask" element={<AskHRI />} />
      </Routes>
    </MemoryRouter>
  )
}

async function send(text) {
  fireEvent.change(screen.getByLabelText('Ask HRI'), { target: { value: text } })
  fireEvent.click(screen.getByRole('button', { name: 'Send' }))
}

beforeEach(() => {
  askHRI.mockReset()
})

describe('AskHRI page', () => {
  it('renders the page with example queries and an empty thread', () => {
    renderAt()
    expect(screen.getByText('Ask HRI')).toBeInTheDocument()
    expect(screen.getByText(/Show me information about HRI-0006/)).toBeInTheDocument()
  })

  it('sends a typed message and shows a loading state', async () => {
    let resolveFn
    askHRI.mockReturnValue(new Promise((resolve) => { resolveFn = resolve }))

    renderAt()
    await send('Why is HRI-0006 high risk?')

    expect(screen.getByText('Why is HRI-0006 high risk?')).toBeInTheDocument()
    expect(screen.getByText(/HRI is looking that up/)).toBeInTheDocument()

    resolveFn({ answer_type: 'prediction', intent: 'risk', message: 'ok', citations: [] })
    await waitFor(() => expect(screen.queryByText(/HRI is looking that up/)).not.toBeInTheDocument())
  })

  it('clears the input and disables Send while a request is in flight', async () => {
    askHRI.mockReturnValue(new Promise(() => {}))
    renderAt()
    await send('Show me HRI-0006')

    expect(screen.getByLabelText('Ask HRI')).toHaveValue('')
    expect(screen.getByRole('button', { name: 'Send' })).toBeDisabled()
  })

  it('renders a successful actual-data response', async () => {
    askHRI.mockResolvedValue({
      answer_type: 'actual',
      intent: 'project',
      message: 'HRI-0006 — a real project.',
      project_id: 'HRI-0006',
      citations: [],
    })
    renderAt()
    await send('Show me information about HRI-0006')

    expect(await screen.findByText('HRI-0006 — a real project.')).toBeInTheDocument()
    expect(screen.getByText('Actual recorded data')).toBeInTheDocument()
  })

  it('renders citations for a document-evidence response', async () => {
    askHRI.mockResolvedValue({
      answer_type: 'document_evidence',
      intent: 'document',
      message: 'From [DOC-001, p. 12]: "some real excerpt"',
      citations: [{ document_id: 'DOC-001', page_number: 12, citation: '[DOC-001, p. 12]', text: 'some real excerpt' }],
    })
    renderAt()
    await send('What do the documents say about cost escalation?')

    expect(await screen.findByText('Document evidence')).toBeInTheDocument()
    expect(screen.getByText('[DOC-001, p. 12]')).toBeInTheDocument()
    expect(screen.getByText('some real excerpt')).toBeInTheDocument()
  })

  it('renders a prediction disclaimer for a model-prediction response', async () => {
    askHRI.mockResolvedValue({
      answer_type: 'prediction',
      intent: 'risk',
      message: 'model says X',
      predictions: { significant_delay_probability: 0.75 },
      citations: [],
      disclaimer: 'These predictions were generated by models trained on synthetic data.',
    })
    renderAt()
    await send('Why is HRI-0006 high risk?')

    expect(await screen.findByText('Model prediction')).toBeInTheDocument()
    expect(screen.getByText(/generated by models trained on synthetic data/)).toBeInTheDocument()
  })

  it('renders a hypothetical disclaimer for a what-if response', async () => {
    askHRI.mockResolvedValue({
      answer_type: 'hypothetical',
      intent: 'whatif',
      message: 'Hypothetical, illustrative only — delay moved from 90 to 95 days.',
      citations: [],
      disclaimer: 'This is a model re-scoring under a hypothetical assumption, not a prediction.',
    })
    renderAt()
    await send('What happens if progress improves by 10% for HRI-0006?')

    expect(await screen.findByText('Hypothetical (what-if)')).toBeInTheDocument()
    expect(screen.getByText(/not a prediction/)).toBeInTheDocument()
  })

  it('renders an unsupported response distinctly, never as fabricated content', async () => {
    askHRI.mockResolvedValue({
      answer_type: 'unsupported',
      intent: 'unsupported',
      message: 'HRI does not have sufficient information to answer that.',
      citations: [],
    })
    renderAt()
    await send('Who will win the next election?')

    expect(await screen.findByText('Not answered')).toBeInTheDocument()
    expect(screen.getByText('HRI does not have sufficient information to answer that.')).toBeInTheDocument()
  })

  it('shows a clear error state when the API request fails', async () => {
    askHRI.mockRejectedValue(new ApiError('Unable to reach the HRI backend.', { status: 0 }))
    renderAt()
    await send('Why is HRI-0006 high risk?')

    expect(await screen.findByText("HRI couldn't process that request.")).toBeInTheDocument()
    expect(screen.getByText('Unable to reach the HRI backend.')).toBeInTheDocument()
  })

  it('passes the project_id query param as page context to every query', async () => {
    askHRI.mockResolvedValue({ answer_type: 'actual', intent: 'project', message: 'ok', citations: [] })
    renderAt('/ask?project=HRI-0006')

    expect(screen.getByText('Context: HRI-0006')).toBeInTheDocument()

    await send('Tell me about this project')
    await waitFor(() => expect(askHRI).toHaveBeenCalledWith('Tell me about this project', 'HRI-0006'))
  })

  it('does not send an empty message', async () => {
    renderAt()
    fireEvent.click(screen.getByRole('button', { name: 'Send' }))
    expect(askHRI).not.toHaveBeenCalled()
  })
})
