import { render, screen, fireEvent } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import DecisionIntelligence from './DecisionIntelligence'
import { getDecisionIntelligence, listProjectSnapshots } from '../api/endpoints'

vi.mock('../api/endpoints', () => ({
  listProjectSnapshots: vi.fn(),
  getDecisionIntelligence: vi.fn(),
}))

const DISCLAIMERS = {
  ml_limitation: 'Model outputs are estimates on a SYNTHETIC dataset.',
  causality_limitation: 'Model feature importance describes association, not causation.',
  scenario_limitation: 'This is a model re-scoring under a hypothetical assumption.',
  evidence_limitation: 'Documentary evidence is limited to a small real-document corpus.',
  inconsistency_limitation: 'Potential inconsistencies require human verification.',
  system_identity: 'This is a prototype decision-support system, not an official NHAI system.',
  synthetic_data_disclaimer: 'These predictions were generated by models trained on SYNTHETIC data.',
}

function baseProject(overrides) {
  return {
    project_id: 'HRI-0006',
    project_name: 'Delhi-Dehradun Expressway',
    state: 'Uttarakhand',
    project_type: 'Expressway',
    contractor: 'ACME Infra',
    highway_number: 'NH-58',
    reporting_month: '2022-12',
    months_since_start: 24,
    project_status: 'Ongoing',
    is_terminal_snapshot: false,
    ...overrides,
  }
}

const BASE_PREDICTIONS = {
  significant_delay: { task: 'significant_delay', model_used: 'random_forest', predicted_class: 1, probability_of_significant_delay: 0.78, actual_value: null },
  final_delay_days: { task: 'final_delay_days', model_used: 'xgboost', predicted_final_delay_days: 94.6, actual_value: null },
  cost_overrun: { task: 'cost_overrun', model_used: 'logistic_regression_baseline', predicted_class: 0, probability_of_cost_overrun: 0.22, actual_value: null },
  final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'linear_regression_baseline', predicted_final_cost_overrun_pct: 8.1, actual_value: null },
}

function riskPositioning(overrides) {
  return {
    status: 'ok',
    message: null,
    cache_computed_at: '2026-09-15T08:36:15',
    cohort_size: 400,
    composite_risk_score: 72.4,
    risk_level: 'HIGH',
    percentile: 88.25,
    delay_risk: 0.7,
    cost_risk: 0.6,
    risk_level_thresholds: { q1: 15.3, q2: 36.2, q3: 65.2 },
    percentile_definition: 'percentile = 100 * count(projects with composite_risk_score <= this project\'s score) / cohort_size.',
    portfolio_relative_disclaimer: 'This risk level/band is PORTFOLIO-RELATIVE. It is NOT an official NHAI threshold.',
    current_risk_basis_note: 'current ongoing-project risk is unavailable in the synthetic corpus.',
    ...overrides,
  }
}

function peerEntry(overrides) {
  return {
    dimension: 'state',
    status: 'ok',
    reason: null,
    value: 'Uttarakhand',
    min_sample_threshold: 15,
    small_sample: false,
    historical: {
      project_count: 22,
      significant_delay_rate: 0.636,
      cost_overrun_rate: 0.41,
      mean_final_delay_days: 88.0,
      mean_final_cost_overrun_pct: 9.5,
    },
    predicted: {
      scored_project_count: 22,
      avg_significant_delay_probability: 0.6,
      avg_cost_overrun_probability: 0.35,
      avg_final_delay_days_predicted: 90.0,
      avg_final_cost_overrun_pct_predicted: 8.0,
      avg_composite_risk_score: 55.0,
      risk_level_counts: { HIGH: 10, MEDIUM: 12 },
    },
    ...overrides,
  }
}

function driverAlignment() {
  return [
    {
      task_key: 'significant_delay',
      matches_serving_model: true,
      live_top_driver: 'progress_efficiency',
      live_top_driver_identity: 'progress_efficiency',
      portfolio_top_driver: 'contractor_productivity_factor',
      portfolio_top_driver_identity: 'contractor_productivity_factor',
      agreement: false,
      comparable: true,
      not_comparable_note: null,
    },
    {
      task_key: 'final_delay_days',
      matches_serving_model: true,
      live_top_driver: 'contractor_productivity_factor',
      live_top_driver_identity: 'contractor_productivity_factor',
      portfolio_top_driver: 'contractor_productivity_factor',
      portfolio_top_driver_identity: 'contractor_productivity_factor',
      agreement: true,
      comparable: true,
      not_comparable_note: null,
    },
    {
      task_key: 'cost_overrun',
      matches_serving_model: false,
      live_top_driver: 'project_age_ratio',
      live_top_driver_identity: 'project_age_ratio',
      portfolio_top_driver: 'cost_tracking_gap_inr_cr',
      portfolio_top_driver_identity: 'cost_tracking_gap_inr_cr',
      agreement: false,
      comparable: false,
      not_comparable_note: 'Not a meaningful comparison -- different model family.',
    },
    {
      task_key: 'final_cost_overrun_pct',
      matches_serving_model: false,
      live_top_driver: 'actual_physical_progress_pct',
      live_top_driver_identity: 'actual_physical_progress_pct',
      portfolio_top_driver: 'cost_tracking_gap_inr_cr',
      portfolio_top_driver_identity: 'cost_tracking_gap_inr_cr',
      agreement: false,
      comparable: false,
      not_comparable_note: 'Not a meaningful comparison -- different model family.',
    },
  ]
}

function baseResponse(overrides) {
  return {
    project: baseProject(),
    prediction_status: 'model_prediction',
    predictions: BASE_PREDICTIONS,
    risk_summary: {
      significant_delay_summary: 'High probability of significant delay.',
      final_delay_days_summary: 'Roughly 95 days of predicted delay.',
      cost_overrun_summary: 'Low probability of cost overrun.',
      final_cost_overrun_pct_summary: 'Roughly 8% predicted cost overrun.',
    },
    risk_drivers: [
      {
        task_key: 'significant_delay',
        label: 'Significant Delay Classification',
        model_used: 'random_forest',
        explainer_type: 'TreeExplainer',
        shap_output_semantics: 'probability contribution',
        top_drivers: [
          { rank: 1, feature: 'progress_efficiency', shap_value: 0.42, direction: 'increases', explanation: 'Lower progress efficiency is associated with higher delay risk.' },
        ],
      },
    ],
    shap_skipped_reason: null,
    documentary_evidence: [
      {
        query: 'land acquisition delay',
        not_found: false,
        answer: 'From [DOC-001, p. 60]: land acquisition delays are a recurring issue.',
        results: [
          {
            rank: 1, similarity_score: 0.61, chunk_id: 'DOC-001-p60-c1', document_id: 'DOC-001', page_number: 60,
            section_heading: null, extraction_method: 'native_text', quality_flag: null, source_filename: 'cag_report.pdf',
            citation: '[DOC-001, p. 60]', text: 'Land acquisition delays are a recurring issue.',
          },
        ],
      },
    ],
    potential_inconsistencies: [],
    scenario: null,
    scenario_skipped_reason: 'Skipped: this snapshot\'s live top driver is categorical.',
    evidence_strength: 'moderate evidence support',
    evidence_strength_basis: 'One relevant document was retrieved for the top model driver.',
    risk_positioning: riskPositioning(),
    peer_context: {
      state: peerEntry(),
      project_type: peerEntry({ dimension: 'project_type', value: 'Expressway' }),
      contractor: peerEntry({ dimension: 'contractor', value: 'ACME Infra', small_sample: true, min_sample_threshold: 8 }),
    },
    driver_alignment: driverAlignment(),
    recommended_reviews: [
      {
        text: 'Review `progress_efficiency` for this project.',
        basis_type: 'model_driver',
        basis_detail: 'Live per-instance top-ranked SHAP feature for: significant-delay.',
      },
      {
        text: "This project's portfolio-relative risk level is HIGH. Its state peer group ('Uttarakhand') has an elevated historical rate.",
        basis_type: 'portfolio_context',
        basis_detail: "Peer-elevated-risk: state='Uttarakhand' historical significant-delay rate 63.6% vs. portfolio-wide 49.3%.",
      },
    ],
    disclaimers: DISCLAIMERS,
    ...overrides,
  }
}

function renderAt(projectId) {
  render(
    <MemoryRouter initialEntries={[`/projects/${projectId}/decision-intelligence`]}>
      <Routes>
        <Route path="/projects/:projectId/decision-intelligence" element={<DecisionIntelligence />} />
        <Route path="/projects/:projectId/risk-summary" element={<div>risk-summary page</div>} />
        <Route path="/projects/:projectId/simulator" element={<div>simulator page</div>} />
      </Routes>
    </MemoryRouter>
  )
}

describe('DecisionIntelligence page: loading and success', () => {
  it('shows a loading state before resolving', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockImplementation(() => new Promise(() => {}))

    renderAt('HRI-0006')
    expect(await screen.findByText(/Computing decision intelligence/)).toBeInTheDocument()
  })

  it('renders executive risk, percentile, peer groups, and driver alignment on success', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(baseResponse())

    renderAt('HRI-0006')

    expect(await screen.findByText(/Delhi-Dehradun Expressway/)).toBeInTheDocument()
    // Portfolio percentile (rendered both in the executive summary and the
    // dedicated Portfolio Position section)
    expect(screen.getAllByText(/88\.3th|88\.2th|88th/).length).toBeGreaterThan(0)
    expect(screen.getAllByText(/High/).length).toBeGreaterThan(0)
    // Peer group cards for all three dimensions
    expect(screen.getAllByText(/Uttarakhand/).length).toBeGreaterThan(0)
    expect(screen.getByText('State Peers')).toBeInTheDocument()
    expect(screen.getByText('Project-Type Peers')).toBeInTheDocument()
    expect(screen.getByText('Contractor Peers')).toBeInTheDocument()
    // Small-sample flag preserved, not dropped
    expect(screen.getByText('Small sample')).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: API error', () => {
  it('shows an error state with retry when the request fails', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockRejectedValue(new Error('network down'))

    renderAt('HRI-0006')
    expect(await screen.findByText(/Unable to load decision intelligence/)).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: cache unavailable / project not in cache', () => {
  it('shows an explicit cache_unavailable message instead of fabricating a percentile', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(
      baseResponse({
        risk_positioning: riskPositioning({
          status: 'cache_unavailable',
          message: 'The portfolio prediction cache has not been generated yet.',
          composite_risk_score: null,
          risk_level: null,
          percentile: null,
          cohort_size: null,
        }),
      })
    )

    renderAt('HRI-0006')
    expect(await screen.findByText('Portfolio prediction cache unavailable.')).toBeInTheDocument()
    expect(screen.getByText(/has not been generated yet/)).toBeInTheDocument()
  })

  it('shows an explicit project_not_in_cache message', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(
      baseResponse({
        risk_positioning: riskPositioning({
          status: 'project_not_in_cache',
          message: 'This project does not have a row in the current portfolio prediction cache.',
          composite_risk_score: null,
          risk_level: null,
          percentile: null,
          cohort_size: 400,
        }),
      })
    )

    renderAt('HRI-0006')
    expect(await screen.findByText('This project is not in the current portfolio prediction cache.')).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: SHAP alignment and non-comparable cost tasks', () => {
  it('renders agree/diverge badges for comparable tasks and the explicit note for non-comparable cost tasks', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(baseResponse())

    renderAt('HRI-0006')
    await screen.findByText(/Delhi-Dehradun Expressway/)

    expect(screen.getByText('Diverges from portfolio')).toBeInTheDocument()
    expect(screen.getByText('Agrees with portfolio')).toBeInTheDocument()
    // Non-comparable cost tasks: no agree/disagree badge, only the note.
    expect(screen.getAllByText('Not a meaningful comparison -- different model family.').length).toBe(2)
    expect(screen.queryAllByText('Diverges from portfolio').length).toBe(1)
  })
})

describe('DecisionIntelligence page: recommendations', () => {
  it('renders merged recommendations with basis_type and basis_detail, including the portfolio_context family', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(baseResponse())

    renderAt('HRI-0006')
    await screen.findByText(/Delhi-Dehradun Expressway/)

    expect(screen.getByText(/Review `progress_efficiency`/)).toBeInTheDocument()
    expect(screen.getByText(/portfolio-relative risk level is HIGH/)).toBeInTheDocument()
    expect(screen.getByText(/Basis: model driver/)).toBeInTheDocument()
    expect(screen.getByText(/Basis: portfolio context/)).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: historical vs predicted / retrospective wording', () => {
  it('labels peer stats as historical vs predicted and shows the retrospective/zero-ongoing note', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(baseResponse())

    renderAt('HRI-0006')
    await screen.findByText(/Delhi-Dehradun Expressway/)

    expect(screen.getAllByText(/Historical significant-delay rate/).length).toBeGreaterThan(0)
    expect(screen.getAllByText(/Predicted avg\. delay probability/).length).toBeGreaterThan(0)
    expect(screen.getByText(/unavailable in the synthetic corpus/)).toBeInTheDocument()
    expect(screen.getByText(/PORTFOLIO-RELATIVE/)).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: terminal snapshot', () => {
  it('skips SHAP and scenario for a terminal snapshot but still shows portfolio context', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2023-06', is_terminal_snapshot: true }])
    getDecisionIntelligence.mockResolvedValue(
      baseResponse({
        project: baseProject({ reporting_month: '2023-06', is_terminal_snapshot: true, project_status: 'Completed' }),
        prediction_status: 'actual_outcome',
        predictions: {
          significant_delay: { task: 'significant_delay', model_used: null, predicted_class: null, probability_of_significant_delay: null, actual_value: 1 },
          final_delay_days: { task: 'final_delay_days', model_used: null, predicted_final_delay_days: null, actual_value: 132 },
          cost_overrun: { task: 'cost_overrun', model_used: null, predicted_class: null, probability_of_cost_overrun: null, actual_value: 0 },
          final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: null, predicted_final_cost_overrun_pct: null, actual_value: 4.2 },
        },
        risk_drivers: [],
        shap_skipped_reason: 'Skipped: this snapshot is terminal and already records the known final outcome.',
        scenario: null,
        scenario_skipped_reason: 'Skipped: this snapshot is terminal, so no live SHAP driver exists to anchor a scenario.',
        driver_alignment: driverAlignment().map((a) => ({ ...a, live_top_driver: null, live_top_driver_identity: null, agreement: null })),
      })
    )

    renderAt('HRI-0006')

    expect(await screen.findByText(/is terminal and already records the known final outcome/)).toBeInTheDocument()
    expect(screen.getByText(/no live SHAP driver exists to anchor a scenario/)).toBeInTheDocument()
    // Portfolio position still renders for a terminal request.
    expect(screen.getByText('Portfolio Position')).toBeInTheDocument()
  })
})

describe('DecisionIntelligence page: what-if navigation', () => {
  it('navigates to the Simulator page for the same project/month', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getDecisionIntelligence.mockResolvedValue(baseResponse())

    renderAt('HRI-0006')
    await screen.findByText(/Delhi-Dehradun Expressway/)

    fireEvent.click(screen.getByRole('button', { name: /Open Simulator/ }))
    expect(await screen.findByText('simulator page')).toBeInTheDocument()
  })
})
