import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi, afterEach } from 'vitest'
import Reports from './Reports'
import { downloadReportPdf, getProject, getRiskSummary, listProjectSnapshots } from '../api/endpoints'
import { ApiError } from '../api/client'

// Phase 13: genuine backend PDF download from the Reports page. These
// tests cover the download button's loading/success/error states -- the
// PDF's actual content is verified against the real backend in
// backend/tests/test_report_pdf.py.
vi.mock('../api/endpoints', () => ({
  getProject: vi.fn(),
  listProjectSnapshots: vi.fn(),
  getRiskSummary: vi.fn(),
  downloadReportPdf: vi.fn(),
}))

const PROJECT = {
  project_id: 'HRI-0006',
  project_name: 'Delhi-Dehradun Expressway',
  state: 'Uttarakhand',
  project_type: 'Expressway',
  contractor: 'ACME Infra',
  highway_number: 'NH-58',
  project_length_km: 210.4,
  planned_start_date: '2020-01-01',
  planned_completion_date: '2024-01-01',
  current_status: 'Ongoing',
}

const RISK_SUMMARY = {
  project: { project_id: 'HRI-0006', reporting_month: '2022-12' },
  prediction_status: 'model_prediction',
  predictions: {
    significant_delay: { probability_of_significant_delay: 0.78, predicted_class: 1, actual_value: null },
    final_delay_days: { predicted_final_delay_days: 94.6, actual_value: null },
    cost_overrun: { probability_of_cost_overrun: 0.22, predicted_class: 0, actual_value: null },
    final_cost_overrun_pct: { predicted_final_cost_overrun_pct: 8.1, actual_value: null },
  },
  risk_summary: {
    significant_delay_summary: 'The model assigns a probability of 78.0% to the significant-delay class.',
    final_delay_days_summary: 'Model-estimated final delay: 94.6 days.',
    cost_overrun_summary: 'The model assigns a probability of 22.0% to the cost-overrun class.',
    final_cost_overrun_pct_summary: 'Model-estimated final cost overrun: 8.1%.',
  },
  evidence_strength: 'high evidence support',
  evidence_strength_basis: 'Relevant documentary evidence was retrieved.',
  potential_inconsistencies: [],
  recommended_reviews: [],
  disclaimers: {
    system_identity: 'This is a prototype decision-support system, not an official NHAI system.',
    ml_limitation: 'Model outputs are estimates on a SYNTHETIC dataset.',
    synthetic_data_disclaimer: 'These predictions were generated by models trained on SYNTHETIC data.',
  },
}

function renderAt(projectId) {
  render(
    <MemoryRouter initialEntries={[`/reports/${projectId}`]}>
      <Routes>
        <Route path="/reports/:projectId" element={<Reports />} />
      </Routes>
    </MemoryRouter>
  )
}

describe('Reports page PDF download', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('shows a "Download PDF Report" action once the report has loaded', async () => {
    getProject.mockResolvedValue(PROJECT)
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getRiskSummary.mockResolvedValue(RISK_SUMMARY)

    renderAt('HRI-0006')

    const button = await screen.findByRole('button', { name: /Download PDF Report/i })
    await waitFor(() => expect(button).toBeEnabled())
  })

  it('requests the real backend PDF and triggers a download on click', async () => {
    getProject.mockResolvedValue(PROJECT)
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getRiskSummary.mockResolvedValue(RISK_SUMMARY)
    const fakeBlob = new Blob(['%PDF-1.4 fake'], { type: 'application/pdf' })
    downloadReportPdf.mockResolvedValue({ blob: fakeBlob, filename: 'HRI-0006_2022-12_HRI_report.pdf' })

    const createObjectURL = vi.fn().mockReturnValue('blob:fake-url')
    const revokeObjectURL = vi.fn()
    global.URL.createObjectURL = createObjectURL
    global.URL.revokeObjectURL = revokeObjectURL

    renderAt('HRI-0006')

    const button = await screen.findByRole('button', { name: /Download PDF Report/i })
    await waitFor(() => expect(button).toBeEnabled())
    fireEvent.click(button)

    await waitFor(() => expect(downloadReportPdf).toHaveBeenCalledWith('HRI-0006', '2022-12'))
    expect(createObjectURL).toHaveBeenCalledWith(fakeBlob)
    await waitFor(() => expect(revokeObjectURL).toHaveBeenCalledWith('blob:fake-url'))
  })

  it('shows an error message when PDF generation fails on the backend', async () => {
    getProject.mockResolvedValue(PROJECT)
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getRiskSummary.mockResolvedValue(RISK_SUMMARY)
    downloadReportPdf.mockRejectedValue(new ApiError("Project 'HRI-0006' not found.", { status: 404 }))

    renderAt('HRI-0006')

    const button = await screen.findByRole('button', { name: /Download PDF Report/i })
    await waitFor(() => expect(button).toBeEnabled())
    fireEvent.click(button)

    expect(await screen.findByText(/Unable to generate the PDF report/i)).toBeInTheDocument()
    expect(screen.getByText(/not found/i)).toBeInTheDocument()
  })

  it('shows an empty state for a project that does not exist', async () => {
    getProject.mockRejectedValue(new ApiError("Project 'HRI-9999' not found.", { status: 404 }))
    listProjectSnapshots.mockResolvedValue([])

    renderAt('HRI-9999')

    expect(await screen.findByText(/was not found/i)).toBeInTheDocument()
  })
})
