import { render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import RiskSummary from './RiskSummary'
import { getRiskSummary, listProjectSnapshots } from '../api/endpoints'

vi.mock('../api/endpoints', () => ({
  listProjectSnapshots: vi.fn(),
  getRiskSummary: vi.fn(),
}))

const DISCLAIMERS = {
  ml_limitation: 'Model outputs are estimates on a SYNTHETIC dataset.',
  causality_limitation: 'Model feature importance describes association, not causation.',
  scenario_limitation: 'This is a model re-scoring under a hypothetical assumption.',
  evidence_limitation: 'Documentary evidence is limited to a small real-document corpus.',
  inconsistency_limitation: 'Potential inconsistencies require human verification.',
  system_identity: 'This is a prototype decision-support system, not an official NHAI system.',
  synthetic_data_disclaimer: 'These predictions were generated by models trained on SYNTHETIC data.',
}

function baseProject(overrides) {
  return {
    project_id: 'HRI-0006',
    project_name: 'Delhi-Dehradun Expressway',
    state: 'Uttarakhand',
    project_type: 'Expressway',
    contractor: 'ACME Infra',
    highway_number: 'NH-58',
    reporting_month: '2022-12',
    months_since_start: 24,
    project_status: 'Ongoing',
    is_terminal_snapshot: false,
    ...overrides,
  }
}

function renderAt(projectId) {
  render(
    <MemoryRouter initialEntries={[`/projects/${projectId}/risk-summary`]}>
      <Routes>
        <Route path="/projects/:projectId/risk-summary" element={<RiskSummary />} />
      </Routes>
    </MemoryRouter>
  )
}

describe('RiskSummary page (non-terminal snapshot)', () => {
  it('renders live SHAP drivers, evidence citations, and the illustrative-scenario label', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getRiskSummary.mockResolvedValue({
      project: baseProject(),
      prediction_status: 'model_prediction',
      predictions: {
        significant_delay: { task: 'significant_delay', model_used: 'RandomForest', predicted_class: 1, probability_of_significant_delay: 0.78, actual_value: null },
        final_delay_days: { task: 'final_delay_days', model_used: 'XGBoost', predicted_final_delay_days: 94.6, actual_value: null },
        cost_overrun: { task: 'cost_overrun', model_used: 'LogisticRegression', predicted_class: 0, probability_of_cost_overrun: 0.22, actual_value: null },
        final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'LinearRegression', predicted_final_cost_overrun_pct: 8.1, actual_value: null },
      },
      risk_summary: {
        significant_delay_summary: 'High probability of significant delay.',
        final_delay_days_summary: 'Roughly 95 days of predicted delay.',
        cost_overrun_summary: 'Low probability of cost overrun.',
        final_cost_overrun_pct_summary: 'Roughly 8% predicted cost overrun.',
      },
      risk_drivers: [
        {
          task_key: 'significant_delay',
          label: 'Significant Delay',
          model_used: 'RandomForest',
          explainer_type: 'TreeExplainer',
          shap_output_semantics: 'log-odds contribution',
          top_drivers: [
            { rank: 1, feature: 'progress_efficiency', shap_value: 0.42, direction: 'increases', explanation: 'Lower progress efficiency is associated with higher delay risk.' },
          ],
        },
      ],
      shap_skipped_reason: null,
      documentary_evidence: [
        {
          query: 'land acquisition delay',
          not_found: false,
          answer: 'From [DOC-001, p. 60]: land acquisition delays are a recurring issue.',
          results: [
            {
              rank: 1,
              similarity_score: 0.61,
              chunk_id: 'DOC-001-p60-c1',
              document_id: 'DOC-001',
              page_number: 60,
              section_heading: null,
              extraction_method: 'native_text',
              quality_flag: null,
              source_filename: 'cag_report.pdf',
              citation: '[DOC-001, p. 60]',
              text: 'Land acquisition delays are a recurring issue.',
            },
          ],
        },
      ],
      potential_inconsistencies: [],
      scenario: {
        field: 'contractor_productivity_factor',
        reference_value: 0.98,
        label: 'Illustrative scenario',
        baseline: {
          significant_delay: { task: 'significant_delay', model_used: 'RandomForest', predicted_class: 1, probability_of_significant_delay: 0.78, actual_value: null },
          final_delay_days: { task: 'final_delay_days', model_used: 'XGBoost', predicted_final_delay_days: 94.6, actual_value: null },
          cost_overrun: { task: 'cost_overrun', model_used: 'LogisticRegression', predicted_class: 0, probability_of_cost_overrun: 0.22, actual_value: null },
          final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'LinearRegression', predicted_final_cost_overrun_pct: 8.1, actual_value: null },
        },
        simulated: {
          significant_delay: { task: 'significant_delay', model_used: 'RandomForest', predicted_class: 0, probability_of_significant_delay: 0.52, actual_value: null },
          final_delay_days: { task: 'final_delay_days', model_used: 'XGBoost', predicted_final_delay_days: 61.2, actual_value: null },
          cost_overrun: { task: 'cost_overrun', model_used: 'LogisticRegression', predicted_class: 0, probability_of_cost_overrun: 0.15, actual_value: null },
          final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'LinearRegression', predicted_final_cost_overrun_pct: 5.4, actual_value: null },
        },
        disclaimer: 'This is a model re-scoring under a hypothetical assumption, not a prediction.',
      },
      scenario_skipped_reason: null,
      recommended_reviews: [],
      evidence_strength: 'moderate evidence support',
      evidence_strength_basis: 'One relevant document was retrieved for the top model driver.',
      disclaimers: DISCLAIMERS,
    })

    renderAt('HRI-0006')

    expect(await screen.findByText(/Delhi-Dehradun Expressway/)).toBeInTheDocument()
    expect(screen.getByText('progress_efficiency')).toBeInTheDocument()
    expect(screen.getByText('[DOC-001, p. 60]')).toBeInTheDocument()
    expect(screen.getByText('Illustrative, not a recommendation')).toBeInTheDocument()
  })
})

describe('RiskSummary page (terminal snapshot)', () => {
  it('skips SHAP and the scenario with explicit reasons instead of fabricating them', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2023-06', is_terminal_snapshot: true }])
    getRiskSummary.mockResolvedValue({
      project: baseProject({ reporting_month: '2023-06', is_terminal_snapshot: true, project_status: 'Completed' }),
      prediction_status: 'actual_outcome',
      predictions: {
        significant_delay: { task: 'significant_delay', model_used: null, predicted_class: null, probability_of_significant_delay: null, actual_value: 1 },
        final_delay_days: { task: 'final_delay_days', model_used: null, predicted_final_delay_days: null, actual_value: 132 },
        cost_overrun: { task: 'cost_overrun', model_used: null, predicted_class: null, probability_of_cost_overrun: null, actual_value: 0 },
        final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: null, predicted_final_cost_overrun_pct: null, actual_value: 4.2 },
      },
      risk_summary: {
        significant_delay_summary: 'Recorded final outcome: significant delay occurred.',
        final_delay_days_summary: 'Recorded final delay of 132 days.',
        cost_overrun_summary: 'Recorded final outcome: no cost overrun.',
        final_cost_overrun_pct_summary: 'Recorded final cost overrun of 4.2%.',
      },
      risk_drivers: [],
      shap_skipped_reason: 'Skipped: this snapshot is terminal and already records the known final outcome.',
      documentary_evidence: [],
      potential_inconsistencies: [],
      scenario: null,
      scenario_skipped_reason: 'Skipped: this snapshot is terminal, so no live SHAP driver exists to anchor a scenario.',
      recommended_reviews: [],
      evidence_strength: 'limited evidence support',
      evidence_strength_basis: 'No evidence queries were run for a terminal snapshot.',
      disclaimers: DISCLAIMERS,
    })

    renderAt('HRI-0006')

    expect(await screen.findByText(/is terminal and already records the known final outcome/)).toBeInTheDocument()
    expect(screen.getByText(/no live SHAP driver exists to anchor a scenario/)).toBeInTheDocument()
    expect(screen.getByText('Recorded final outcome')).toBeInTheDocument()
  })
})
