import { render, screen, fireEvent } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import Simulator from './Simulator'
import { getProjectSnapshot, listProjectSnapshots, runSimulation } from '../api/endpoints'

vi.mock('../api/endpoints', () => ({
  listProjectSnapshots: vi.fn(),
  getProjectSnapshot: vi.fn(),
  runSimulation: vi.fn(),
}))

function renderAt(projectId) {
  render(
    <MemoryRouter initialEntries={[`/projects/${projectId}/simulator`]}>
      <Routes>
        <Route path="/projects/:projectId/simulator" element={<Simulator />} />
      </Routes>
    </MemoryRouter>
  )
}

const NON_TERMINAL_SNAPSHOT = {
  project_id: 'HRI-0006',
  reporting_month: '2022-12',
  is_terminal_snapshot: false,
  land_acquisition_delay_days: 40,
  utility_shifting_delay_days: 10,
  environment_clearance_delay_days: 5,
  material_delay_days: 3,
  labour_shortage_days: 0,
  equipment_unavailability_days: 0,
  weather_disruption_days: 8,
  traffic_diversion_delay_days: 2,
  design_change_delay_days: 0,
  approval_delay_days: 6,
  contractor_productivity_factor: 0.98,
  planned_physical_progress_pct: 55,
  actual_physical_progress_pct: 48,
  planned_financial_progress_pct: 50,
  actual_financial_progress_pct: 44,
}

describe('Simulator page', () => {
  it('shows a clear explanation instead of a form when the selected snapshot is terminal', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2023-06', is_terminal_snapshot: true }])
    getProjectSnapshot.mockResolvedValue({ ...NON_TERMINAL_SNAPSHOT, reporting_month: '2023-06', is_terminal_snapshot: true })

    renderAt('HRI-0006')

    expect(await screen.findByText(/Simulation is unavailable for this snapshot/)).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /run simulation/i })).not.toBeInTheDocument()
  })

  it('renders override inputs for a non-terminal snapshot and runs a simulation', async () => {
    listProjectSnapshots.mockResolvedValue([{ reporting_month: '2022-12', is_terminal_snapshot: false }])
    getProjectSnapshot.mockResolvedValue(NON_TERMINAL_SNAPSHOT)
    runSimulation.mockResolvedValue({
      project_id: 'HRI-0006',
      reporting_month: '2022-12',
      is_terminal_snapshot: false,
      overrides: [{ field: 'contractor_productivity_factor', original_value: 0.98, simulated_value: 0.5, delta: -0.48 }],
      extrapolation_warnings: [],
      baseline_predictions: {
        significant_delay: { task: 'significant_delay', model_used: 'RandomForest', predicted_class: 1, probability_of_significant_delay: 0.78, actual_value: null },
        final_delay_days: { task: 'final_delay_days', model_used: 'XGBoost', predicted_final_delay_days: 94.6, actual_value: null },
        cost_overrun: { task: 'cost_overrun', model_used: 'LogisticRegression', predicted_class: 0, probability_of_cost_overrun: 0.22, actual_value: null },
        final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'LinearRegression', predicted_final_cost_overrun_pct: 8.1, actual_value: null },
      },
      simulated_predictions: {
        significant_delay: { task: 'significant_delay', model_used: 'RandomForest', predicted_class: 1, probability_of_significant_delay: 0.91, actual_value: null },
        final_delay_days: { task: 'final_delay_days', model_used: 'XGBoost', predicted_final_delay_days: 116.5, actual_value: null },
        cost_overrun: { task: 'cost_overrun', model_used: 'LogisticRegression', predicted_class: 1, probability_of_cost_overrun: 0.4, actual_value: null },
        final_cost_overrun_pct: { task: 'final_cost_overrun_pct', model_used: 'LinearRegression', predicted_final_cost_overrun_pct: 13.2, actual_value: null },
      },
      synthetic_data_disclaimer: 'These predictions were generated by models trained on SYNTHETIC data.',
      simulation_disclaimer: 'This is a model re-scoring under a hypothetical assumption, not a prediction of what will actually happen.',
    })

    renderAt('HRI-0006')

    const productivityInput = await screen.findByLabelText('Contractor Productivity Factor')
    expect(productivityInput).toHaveValue(0.98)

    fireEvent.change(productivityInput, { target: { value: '0.5' } })
    fireEvent.click(screen.getByRole('button', { name: /run simulation/i }))

    expect(await screen.findByText('Baseline vs Simulated')).toBeInTheDocument()
    expect(runSimulation).toHaveBeenCalledWith('HRI-0006', '2022-12', { contractor_productivity_factor: 0.5 })
    expect(screen.getByText(/This is a model re-scoring under a hypothetical assumption/)).toBeInTheDocument()
  })
})
